# Generated by Django 6.0.4 on 2026-04-21 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10)),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=10)),
                ('raca', models.CharField(blank=True, max_length=100, verbose_name='raça')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_processo', 'Em processo de adoção'), ('adotado', 'Adotado')], default='disponivel', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='pets.pet')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_adocao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação de adoção',
                'verbose_name_plural': 'solicitações de adoção',
                'ordering': ['-data_solicitacao'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'pet'), name='solicitacao_unica_por_usuario_pet')],
            },
        ),
    ]
